export default ()=>{
  return [
    {
      name:"any",
      configuration:{
      },
      stats:{
        personal:{
          numberOfWords:34,
          numberOfWordsWithOneMistake:12,
          wordsDone:123,
          wordsRejected:2,
          fails:23,
          overallTime:12233,
          testTimeAvg:3
        },
        avg:{
          wordsDone:123,
          wordsRejected:2,
          fails:23,
          overallTime:12233,
          testTimeAvg:3
        }
      }
    },
    {
      name:"any",
      configuration:{
      },
      stats:{
        personal:{
          numberOfWords:34,
          numberOfWordsWithOneMistake:12,
          wordsDone:123,
          wordsRejected:2,
          fails:23,
          overallTime:12233,
          testTimeAvg:3
        },
        avg:{
          wordsDone:123,
          wordsRejected:2,
          fails:23,
          overallTime:12233,
          testTimeAvg:3
        }
      }
    },
    {
      name:"any",
      configuration:{
      },
      stats:{
        personal:{
          numberOfWords:34,
          numberOfWordsWithOneMistake:12,
          wordsDone:123,
          wordsRejected:2,
          fails:23,
          overallTime:12233,
          testTimeAvg:3
        },
        avg:{
          wordsDone:123,
          wordsRejected:2,
          fails:23,
          overallTime:12233,
          testTimeAvg:3
        }
      }
    },
    {
      name:"any",
      configuration:{
      },
      stats:{
        personal:{
          numberOfWords:34,
          numberOfWordsWithOneMistake:12,
          wordsDone:123,
          wordsRejected:2,
          fails:23,
          overallTime:12233,
          testTimeAvg:3
        },
        avg:{
          wordsDone:123,
          wordsRejected:2,
          fails:23,
          overallTime:12233,
          testTimeAvg:3
        }
      }
    },
    {
      name:"any",
      configuration:{
      },
      stats:{
        personal:{
          numberOfWords:34,
          numberOfWordsWithOneMistake:12,
          wordsDone:123,
          wordsRejected:2,
          fails:23,
          overallTime:12233,
          testTimeAvg:3
        },
        avg:{
          wordsDone:123,
          wordsRejected:2,
          fails:23,
          overallTime:12233,
          testTimeAvg:3
        }
      }
    }
  ]
}
